### ISSUE TITLE
Disable for TypeScript 4.2+

### ISSUE THREAD

**Issue by mjbvz** [aeschli/typescript-vscode-sh-plugin#22]
Semantic highlighting support should now be built into the TypeScript server. We should :

- Quickly test to make sure there are no major regressions with the native TypeScript support
- Disable this plugin by default when the plugin is run with TypeScript 4.2
- At some point in the future (after giving users enough time to update to newer TS versions) stop including this plugin with VS Code.

**Comment by aeschli** [comment]
I tested that the tests also run with the built-in '2020' typescript support.
The plugin will not intercept when in >= 4.2

**Comment by jasonlyu123** [comment]
Hi. As far as I know. typescript's built-in semantic highlighting doesn't work with js files. 
https://github.com/microsoft/TypeScript/blob/b1571fcb71501d16f21173979365d4c4d53a11cb/src/services/services.ts#L1888

I checked with the insider version of vscode. Semantic highlight no longer show up on js files on 1.55.0 insider with commit d06d2f1d6245ce00b1c36a9cd81a9087d225173e. 

insider version:
![圖片](https://user-images.githubusercontent.com/36730922/112819395-2212bb80-90b7-11eb-88ca-f770b475f694.png)

1.54:
![圖片](https://user-images.githubusercontent.com/36730922/112819812-8afa3380-90b7-11eb-8451-0b09298fc2e6.png)
